module.exports.ELITE_TEAM_NAMES = [
  "blue",
  "dark-green",
  "orange",
  "green",
  "red",
  "sky-blue",
];

module.exports.ELITE_TEAMS = {
  blue: {
    color: "3d5dff",
    captain: "Tareek",
    vice: "Cloak",
    members: [
      "Death.",
      "M.S Azurite",
      "𝚇𝚎𝚗𝚘𝚗⁵⁴",
      "🌟Taweek🌟",
      "?cars!",
      "COWTER",
      "OG",
      "Spinner",
      "Shooty",
      "someday",
      "𝔻𝙵",
      "Cyaintu",
      "Chai",
      "0⇂2345678910",
      "Exited sauc",
      "Xazte",
      "Prodigy",
      "Crayfish"
    ],
  },
  "dark-green": {
    color: "008037",
    captain: "@==",
    vice: "sd:)",
    members: [
      "𝟙𝟡𝟠𝟜",
      "choerry",
      "wam",
      "wow",
      "Person",
      "Mongoose",
      "Amy",
      "lagmaster",
      "M Eddy",
      ],
  },
  orange: {
    color: "ff8a2a",
    captain: "unteamer",
    vice: "MadKate",
    members: [
     "PolinkaZ",
      "Coder Cat",
      "H A N G R Y",
      "Fat Jess",
      "LvlUp",
      "Timmey",
      "Midnight",
      "Lula",
      "Grim",
      "_I_Ne_I_",
      "IceSword2",
      "Sanitarium",
      "TowerBuilder",
      "NewHampshir",
      "TRAIN MASTER",
      "rycbar",
    ],
  },
  green: {
    color: "18e21f",
    captain: "Böömer",
    vice: "kTTY",
    members: [
      "Böömer",
      "......",
      "Whassup",
      "Flock",
      "ɀεɲǿᵪˢʸˢ",
      "goldenNUGGET",
      "Tea",
      "spectator",
      "Rivale ♠",
      "Fatale ♠️",
      "℣ＯＲＴＥＸ渦",
      "Parker wins",
      "ֆӄօʀɖʀǟɛƈ",
      "Goated",
      "Yifei is bad",
    ],
  },
  red: {
    color: "fd3535",
    captain: "ANDYMAN",
    vice: "MrJack",
    members: [
     "I'm Innocent",
      "Hobz 👀",
      "Steve",
      "Bahoo Ug Tae",
      "Kopta",
      "Pepsi",
      "Tez?",
      "Ethn",
      "Happy Potato",
      "$KingAaron$",
      "Meatloaf",
      "e",
      "Jet",
      "Nope",
      "buildy",
    ],
  },
  "sky-blue": {
    color: "55d5ff",
    captain: "⛈️Thunder⛈️",
    vice: "Blaze",
    members: [
      "Player-36",
      "HerozeR",
      "Lukey",
      "Hᴀᴠᴏᴄ",
      "Fun Mup",
      "Master Yoda",
      "Ascent",
      "Emma",
      "Isra",
      "SundaySchool",
      "sw3",
      "GoldenGoat",
      "Iclimbhigher",
      "Wave",
      "zain",
      "sw5",
      "A12"
    ],
  },
};
